### ISSUE TITLE
Command line option for config location

### ISSUE THREAD

**Issue by glugy** [etcinit/phabulous#12]
I'm using phabulous on a FreeBSD system, and I've found that phabulous only picks up the config file if my shell session is in the same directory as the phabulous executable.  This makes it difficult to daemonize phabulous and treat it as a service.  I saw that it's possible to use environment variables to store the config settings, but I wonder if it might be easier to be able to specify the config location on the command line such as `/usr/local/bin/phabulous --config /usr/local/etc/phabulous/main.yml serve`.

**Comment by etcinit** [comment]
Implemented in latest release.
