### ISSUE TITLE
Index out of range - differential.go:47

### ISSUE THREAD

**Issue by akinsella** [etcinit/phabulous#19]
Hi, 

I use the 2.3 version.

Here is recurring log available in std output:

'''
2016/01/27 17:11:15 Panic recovery -> runtime error: index out of range
/usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:423 (0x42abc9)
/usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:12 (0x4290a9)
/Users/etcinit/go/src/github.com/etcinit/phabulous/app/resolvers/differential.go:47 (0x5dee03)
/Users/etcinit/go/src/github.com/etcinit/phabulous/app/controllers/feed.go:90 (0x543bcf)
/Users/etcinit/go/src/github.com/etcinit/phabulous/app/controllers/feed.go:29 (0x544bca)
/Users/etcinit/go/src/github.com/gin-gonic/gin/context.go:95 (0x54509a)
/Users/etcinit/go/src/github.com/gin-gonic/gin/logger.go:56 (0x556541)
/Users/etcinit/go/src/github.com/gin-gonic/gin/context.go:95 (0x54509a)
/Users/etcinit/go/src/github.com/gin-gonic/gin/recovery.go:43 (0x5570a1)
/Users/etcinit/go/src/github.com/gin-gonic/gin/context.go:95 (0x54509a)
/Users/etcinit/go/src/github.com/gin-gonic/gin/gin.go:294 (0x54baf2)
/Users/etcinit/go/src/github.com/gin-gonic/gin/gin.go:275 (0x54b727)
/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1862 (0x5fe5fe)
/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1361 (0x5fbc3e)
/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 (0x45c141)
'''

**Comment by amckinley** [comment]
seeing the same thing:

`2016/04/05 23:45:38 Panic recovery -> runtime error: index out of range
/usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:423 (0x42abc9)
/usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:12 (0x4290a9)
/Users/etcinit/go/src/github.com/etcinit/phabulous/app/resolvers/differential.go:47 (0x5dee03)
/Users/etcinit/go/src/github.com/etcinit/phabulous/app/controllers/feed.go:90 (0x543bcf)
/Users/etcinit/go/src/github.com/etcinit/phabulous/app/controllers/feed.go:29 (0x544bca)
/Users/etcinit/go/src/github.com/gin-gonic/gin/context.go:95 (0x54509a)
/Users/etcinit/go/src/github.com/gin-gonic/gin/logger.go:56 (0x556541)
/Users/etcinit/go/src/github.com/gin-gonic/gin/context.go:95 (0x54509a)
/Users/etcinit/go/src/github.com/gin-gonic/gin/recovery.go:43 (0x5570a1)
/Users/etcinit/go/src/github.com/gin-gonic/gin/context.go:95 (0x54509a)
/Users/etcinit/go/src/github.com/gin-gonic/gin/gin.go:294 (0x54baf2)
/Users/etcinit/go/src/github.com/gin-gonic/gin/gin.go:275 (0x54b727)
/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1862 (0x5fe5fe)
/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1361 (0x5fbc3e)
/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 (0x45c141)`

**Comment by etcinit** [comment]
I added a very simple check for handling this error. However, this means that these feed messages won't be matched with a repository, therefore, they won't be routed to the project's channel.

I would check and make sure that the bot's account has access for viewing the repositories.

**Comment by schemar** [comment]
This should be fixed in the upcoming 3.0.0 release.
