### ISSUE TITLE
Ability to filter the feed

### ISSUE THREAD

**Issue by srijan** [etcinit/phabulous#2]
It would be good to have a way to only send some feed items to slack.

For example, only feed items related to a particular project, or only send Diffusion Commits, etc..

**Comment by etcinit** [comment]
Hi. I've made some progress towards this. So far I've been routing Diffusion Commits to specific Slack rooms. Checkout the [go](https://github.com/etcinit/phabricator-slack-feed/tree/go) branch if you would like to try it out. I don't have any docs yet though :sweat_smile:

**Comment by etcinit** [comment]
This is now supported for Commits, Revisions, and Tasks. Checkout the `README.md` on how to set it up. :)
