### ISSUE TITLE
Version number in Help does not match effective binary version

### ISSUE THREAD

**Issue by akinsella** [etcinit/phabulous#20]
Hi,

The version number in Help does not match effective version of tool. I have setup version 2.3.0, and it shows 2.1.0-alpha1

**Comment by berkus** [comment]
There's one more place missing - https://github.com/etcinit/phabulous/blob/develop/app/controllers/front.go#L25 this uses hardcoded version number, instead of configured app number.

**Comment by etcinit** [comment]
Fixed on 8e669fd33fd4637253a1a245922ad9dc6824946a
