### ISSUE TITLE
Question - Does this work with Phacility hosted installs?

### ISSUE THREAD

**Issue by joncalhoun** [etcinit/phabulous#24]
We currently run on a Phacility hosted install of Phabricator. Would this work for that if we just used the Phabulous server IP instead of localhost for the hooks?

**Comment by etcinit** [comment]
- Feed stuff should work on remote servers. However, you will need to check if they allow you to modify that setting.
- The conduit related features should work fine (e.g. Looking up a task by typing out the ID).

**Comment by MikeMcMahon** [comment]
can confirm this works fine, as long as you have full access to manage the instance you can update the feed.http-hooks setting.
