### ISSUE TITLE
Accept indirect commands as part of longer string

### ISSUE THREAD

**Issue by staii** [etcinit/phabulous#31]
When someone in the chat refers to a Phabricator object, I'd love if Phabulous saw it as an indirect command.

For example, if someone says "I really like what you did on T21", Phabulous could reply with the equivalent of the "T21" indirect command.

I understand this might include false positives at times (although I believe it is unlikely), but I don't think those would be annoying.

**Comment by schemar** [comment]
This is part of the latest beta release.
