### ISSUE TITLE
json: cannot unmarshal object into Go value of type []interface {}

### ISSUE THREAD

**Issue by 3c7** [etcinit/phabulous#33]
Hey,

getting this error when using phabulous to publish a specific project into a slack channel:
`(*json.UnmarshalTypeError)(0xc82042a180)(json: cannot unmarshal object into Go value of type []interface {})`
followed by
`[GIN] 2016/05/15 - 00:14:29 | 200 |  823.713756ms | 127.0.0.1 |   POST    /v1/feed/receive`.
When I'm using the complete feed functionality it works, but I only want messages to a specific project, so I think it is properly configurated. I'm able to `lookup` the events correctly:

```
3c7 [00:57] 
@phabulous-bot: lookup T41
Phabulous Bot [00:57] 
​*T41: Test 4*​ (open): https://phabricator.xxxxxx.xx/T41
```

But the bot doesn't publish them when they get created.

Best regards
Nils

Edit: Sorry, I've absolute no clue about Go. :smile: Took a look at the src but it's way too unfamiliar to me, so I can't make a pull reqest.

**Comment by etcinit** [comment]
Probably related to #27
