### ISSUE TITLE
phabulous serve just hangs and doesn't bind on an ip address

### ISSUE THREAD

**Issue by chrismann41** [etcinit/phabulous#35]
I've followed the documentation to set up phabulous, but when I run phabulous serve, it seems to spawn three children and then just sits there, with out binding up on any IP address.

Is there a way to log what's going on to help troubleshoot this?

**Comment by chrismann41** [comment]
I was stupid. Got some help compiling the binary.

**Comment by etcinit** [comment]
:+1:
