### ISSUE TITLE
Update Phabricator Logo

### ISSUE THREAD

**Issue by chadlittle** [etcinit/phabulous#42]
Here's a hi-res of the new logo. Thanks!

![logo_large_white_v8](https://cloud.githubusercontent.com/assets/1045295/18281642/7c9c9894-7412-11e6-9230-94f3ac68dc48.png)

**Comment by chadlittle** [comment]
(it's really there, I swear)

**Comment by etcinit** [comment]
Thanks, will update the bot avatar soon 👍
