### ISSUE TITLE
Create repositories-only feed channel

### ISSUE THREAD

**Issue by bcorcoran** [etcinit/phabulous#46]
Hi,

I have a pretty small organization and I think it would be quite useful to have ONLY repository feed information posted to a channel... basically the same as "feed" but only repository commits/revisions without the need to specify every callsign.

I'm getting "flooded" with messages because there are honestly too many things in the feed by default, so having a "repos only" option for the feed items would be great.

**Comment by etcinit** [comment]
Implemented in `master`. This should be in the next release (`v3.0.0-beta2` or `v3.0.0`). https://github.com/etcinit/phabulous/blob/master/config/main.yml#L73
