### ISSUE TITLE
Too long to start the server

### ISSUE THREAD

**Issue by virt87** [etcinit/phabulous#52]
Hi. I have followed the guide and tried to install phabulous , but it tooks too much time to start it. After 15min, I definitely thought something is wrong. Any advice?

How to repeat:
1) install the version
2) try running 
    ./phabulous serve

Settings:
1) debian jessy
2) phabulous_3.0.0-beta1_linux_amd64

**Comment by virt87** [comment]
Any debug mode to see why the script doesn't exit?

**Comment by etcinit** [comment]
Debug mode can be enabled on https://github.com/etcinit/phabulous/blob/master/config/main.yml#L17. It mainly causes output to be more verbose.

I can't think of much that would cause the server to halt for 15+ minutes on boot. Only thing that comes to mind is perhaps network issues?

To rule out issues with your setup/distribution, you could try to use the Docker image. However, the image is based on Debian as well.

**Comment by virt87** [comment]
I have finally found how to start it but is it normal that the script that launch the pbaulous server doesn't return?
![screen shot 2017-03-11 at 10 57 46](https://cloud.githubusercontent.com/assets/1911418/23821625/9a868dc8-0649-11e7-8b01-368fabe491e8.png)
