### ISSUE TITLE
React on any mention of a TXXX or DXXX

### ISSUE THREAD

**Issue by schemar** [etcinit/phabulous#59]
Given that I am in a slack channel together with phabulous
When I write something like "Please have a look at T1000"
Then phabulous should write: "T1000: ticket description"
But instead phabulous is silent

Is there an option to enable this already? If not, it would be nice to have this, maybe configurable. I would be willing to create a pull request for this.

**Comment by farshidce** [comment]
Yes it would be very helpful  to add this features. From what I understand this logic can be added to feed controller . If that’s the right place to add this logic I can send a PR.

**Comment by schemar** [comment]
Hey @farshidce thanks for the offer!

From my understanding the regular expressions of `LookupCommand::get{,IM,Mention}Matchers()` are responsible for regular patterns that identify messages.
Right now they are strict, including line beginning and ending, e.g. `"^([T|D][0-9]{1,16})$"`. Those should be made more flexible to allow for "in-line" matching.
The question is whether this should be configurable or whether we should change the default behavior. From my point of view, changing the default behavior is OK, but maybe not everyone agrees.

**Comment by cwlbraa** [comment]
The default behavior will still work, so this seems like a purely additive change to me, and would dramatically improve my user experience with this plugin. I'd also love to see multiple ticket mentions in a single message supported.

**Comment by seglo** [comment]
I was hoping for exactly this feature when I was looking for something like phabulous.  Akin to the old knowledge base bots I remember from various IRC channels.  

@schemar Have you considered submitting a PR?

**Comment by seglo** [comment]
Subscribed. Thanks!
