### ISSUE TITLE
Maintainer Offered

### ISSUE THREAD

**Issue by schemar** [etcinit/phabulous#62]
Hey @etcinit 

it seems you have no time anymore to maintain this repository. I would offer to take over. I can create some pull requests, if you'd like, but it seems you won't read those anyways :(

Cheers,
Martin

**Comment by etcinit** [comment]
Hi @schemar,

I've added you as a collaborator. Thanks for your interest in the project.

I've been wanting to merge all the pending PRs but I recently switched jobs and need to check with my manager before working on a OSS project. I think the process is super simple but I've been putting it off. 😅

Anyhow, you are not bound by this, so merge away! :)
