### ISSUE TITLE
Transient slack auth errors

### ISSUE THREAD

**Issue by seglo** [etcinit/phabulous#65]
I followed the Getting Started guide and run into errors that indicate my slack auth is not working.  I execute `./phabulous serve` in debug mode and see a lot of log lines that appear to be data from slack which includes channel and user data, but after a few seconds the logs indicate there was a slack auth issue.

phabulous joins configured channel with message: `Hi! Phabulous v3 reporting for duty!`, then goes offline.

Logs:

```
time="2018-01-02T19:01:53Z" level=debug msg="Logger is debug level."
time="2018-01-02T19:01:53Z" level=debug msg="Booted upper layer."
time="2018-01-02T19:01:53Z" level=info msg="Starting RTM handler..."
time="2018-01-02T19:01:53Z" level=info msg="Starting up the API server..."
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET   /                         --> github.com/etcinit/phabulous/app/controllers.(*FrontController).(github.com/etcinit/phabulous/app/controllers.getIndex)-fm (3 handlers)
[GIN-debug] GET   /healthcheck              --> github.com/etcinit/phabulous/app/controllers.(*FrontController).(github.com/etcinit/phabulous/app/controllers.getHealthCheck)-fm (3 handlers)
[GIN-debug] POST  /v1/feed/receive          --> github.com/etcinit/phabulous/app/controllers.(*FeedController).(github.com/etcinit/phabulous/app/controllers.postReceive)-fm (3 handlers)
time="2018-01-02T19:01:53Z" level=debug msg="API Server Hostname: :8085"
[GIN-debug] Listening and serving HTTP on :8085
time="2018-01-02T19:01:53Z" level=debug msg="RTM Event received."
time="2018-01-02T19:01:53Z" level=info msg="Attempting to connect to Slack (Attempt #1)"
time="2018-01-02T19:01:54Z" level=debug msg="RTM Event received."
(big user data blob log lines)
time="2018-01-02T19:01:54Z" level=debug msg="Connection counter: 1"
time="2018-01-02T19:01:54Z" level=info msg="Bot Slack ID:  U8MAN9WG5"
time="2018-01-02T19:01:54Z" level=debug msg="RTM Event received."
time="2018-01-02T19:01:54Z" level=debug msg="RTM Event received."
time="2018-01-02T19:01:54Z" level=debug msg="RTM Event received."
time="2018-01-02T19:01:54Z" level=info msg="Attempting to connect to Slack (Attempt #1)"
time="2018-01-02T19:01:54Z" level=debug msg="RTM Event received."
time="2018-01-02T19:01:54Z" level=error msg="Unable to connect/authenticate with Slack. Check the bot's credentials."
time="2018-01-02T19:01:54Z" level=debug msg="RTM Event received."
time="2018-01-02T19:01:54Z" level=info msg="Attempting to connect to Slack (Attempt #2)"
time="2018-01-02T19:01:54Z" level=debug msg="RTM Event received."
...
```

**Comment by d0ug7a5** [comment]
I am experiencing the same symptoms. Our setup is Phabulous running in Docker, and it works intermittently. With debug on, we see the same as seglo above.

Although our notifications from Phabricator do come through, they are interspersed with a lot of `Hi! Phabulous v3 reporting for duty!`; I think this happens maybe every time the connection fails but haven't investigated that fully yet.

I don't know if Slack have changed something with their Real Time API - I couldn't find anything obvious, but I'm not sure what other explanation there could be 🤔 

Dougie R
Football Radar Devs twitter.com/fr_devs

PS We love Phabulous, thanks for making it 😄

**Comment by schemar** [comment]
Does the issue also occur when you are not using debug mode?

**Comment by seglo** [comment]
@schemar Yes, it did for me.  Some other notes on the behaviour:

* It takes anywhere from a second to 10 seconds before the errors are logged to the console
* Each run, there will be multiple `Hi! Phabulous v3 reporting for duty!` messages in my slack channel, I assume for each successful connection.

**Comment by CrowdSparkDave** [comment]
Same here.

**Comment by okomestudio** [comment]
This started happening to me this morning. We are still using v2 but seeing the "reporting for duty" message every other minute or so. Something likely changed on the Slack... we have not changed anything, and other than those messages things seem working as they have been.

**Comment by Gussi** [comment]
Same is happening here, started happening yesterday. Channel gets flooded with `Hi! Phabulous v3 reporting for duty!` and terminal with `ERRO[72782] Unable to connect/authenticate with Slack. Check the bot's credentials.`.

I'm guessing slack must've changed something with their API.

**Comment by schemar** [comment]
I don't really see anything relevant, I think https://api.slack.com/changelog

**Comment by d0ug7a5** [comment]
I thought it _might_ be this but I haven't looked at it properly to check in depth https://api.slack.com/changelog/2017-10-making-rtm-presence-subscription-only

**Comment by d0ug7a5** [comment]
I've contacted the person in the tweet above; he is using the same Slack library used in Phabulous. 

Apparently [what they did](https://twitter.com/mikekarlesky/status/951453794470105088) to solve this was to update to a more recent version of the plugin, and everything is working for them again now.

**Comment by sbahra** [comment]
Encountering this issue as well with latest beta release.

**Comment by schemar** [comment]
I rebuilt phabulous with an updated release of [nlopes/slack](https://github.com/nlopes/slack). It works now for me as far as I can tell. I made two new [Releases](https://github.com/etcinit/phabulous/releases).

Can you please confirm that it works with the new binaries?

**Comment by d0ug7a5** [comment]
This appears to be working perfectly - many thanks @schemar!

**Comment by schemar** [comment]
Thanks @d0ug7a5!
I am closing this issue now. Please re-open it in case it is not fixed.

**Comment by seglo** [comment]
The latest release is working as expected.  Thank you @schemar and @d0ug7a5 .

**Comment by gurudave** [comment]
I'm seeing what looks like the same problem. I've tried 3.0.0_beta2 and beta3. I also couldn't get a connection with 2.3 either - it didn't produce an error, but the bot didn't seem to connect to Slack either. Could anyone suggest anything to try to fix/debug the issue?

**Comment by schemar** [comment]
Did you set up the configuration correctly?

**Comment by raphaelsoul** [comment]
This error occurs again with docker version.
Curl response is 
`{"messages":["Welcome to the Phabulous API"],"status":"success","version":"2.4.0-beta1"}`

Using `latest` tag. Is that a wrong build on docker ?
@schemar

**Comment by schemar** [comment]
Sorry @raphaelsoul I am not maintaining this project any longer. We need a new maintainer.
