### ISSUE TITLE
Certificates deprecated, cannot connect with newest phabricator

### ISSUE THREAD

**Issue by AtomicTroop** [etcinit/phabulous#9]
In a fresh Phabricator install, the Conduit Certificate feature has been removed as obsolete. It has been replaced with API Tokens. Gonduit (and by proxy, Phabulous) rely on connecting with a certificate so both are basically unusable on newer phabricator versions.

Here's the relevant changelog.
https://secure.phabricator.com/w/changelog/2015.45/#upgrading-compatibility

**Comment by etcinit** [comment]
Fixed in version 2.2.
